### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by KiranBaliga** [muruga21/LoadDistrix#1]
I’d like to add a Code of Conduct to the repository to help you create a positive environment. Please let me know if it’s okay to proceed.

**Comment by muruga21** [comment]
@KiranBaliga Yeah dude.. add Code of Conduct

**Comment by ghost** [comment]
@muruga21 Please review the PR and action accordingly. Please add level1 and gssoc24-ext to the PR. Thank you
