### ISSUE TITLE
Health Check Alerts

### ISSUE THREAD

**Issue by sv410** [muruga21/LoadDistrix#14]
Extend health checks to send alerts (e.g., email or Slack notifications) when a backend server becomes unresponsive.
Benefit: Provides insights into system performance, helping to identify bottlenecks and improve troubleshooting.

**Comment by muruga21** [comment]
@sv410 yeah it would be a cool feature.. can you elaborate what you gonna do..?

**Comment by sv410** [comment]
Health Check Function: The healthCheck function iterates through the list of servers, sending an HTTP GET request to each. If a server is down (i.e., the request fails or returns a non-200 status code), it marks the server as down and sends an alert.
Send Alert Function: The sendAlert function uses the gomail package to send an email notification. You can replace this with any other notification service as needed.
Main Function: The main function sets up a ticker to run the health check every 30 seconds.

**Comment by muruga21** [comment]
@sv410 Great !

**Comment by sv410** [comment]
#14 completed pls level up if u like the work to level3
