### ISSUE TITLE
Add Github Greetings Bot

### ISSUE THREAD

**Issue by KiranBaliga** [muruga21/LoadDistrix#3]
I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (GSSoC24 Contribution)

**Comment by ramu-nukavarapu** [comment]
So whenever we raise an issue or a pull request in this repo, the bot has to greet the users. Right.

**Comment by ghost** [comment]
@ramu-nukavarapu Are you the project maintainer of this repo, can you please assign this task to me, I have originally requested for the enhancment.

**Comment by muruga21** [comment]
@KiranBaliga can you give or show us some example greeting from the bot..

**Comment by ramu-nukavarapu** [comment]
@KiranBaliga No. I'm also one of the contributor in GSSoC. The greeting bot looks interesting, so that's why I commented on it to contribute

**Comment by ghost** [comment]
@muruga21 It will send out a message like "Thank you for your interest. Our team will review it and get back to you as soon as possible" or "Thank you for your contribution. Your efforts are highly valued. Please wait for our maintainer to review the request".

**Comment by ramu-nukavarapu** [comment]
@muruga21 can I give an example for that

**Comment by ghost** [comment]
@muruga21 This is a level1 enhancement. So whenever a new user creates a new PR or issue, the bot will come in action.

**Comment by muruga21** [comment]
@ramu-nukavarapu i can see your interest, but kiran was the first person to raise this issue.. so im gonna assign this task to @KiranBaliga

**Comment by ramu-nukavarapu** [comment]
@muruga21 yeah that's completely fine. He is the one who raised this issue.

**Comment by ghost** [comment]
@muruga21 Please review the PR and action accordingly.

**Comment by ghost** [comment]
Thank you!
