### ISSUE TITLE
[Feature] configuration flexibility 

### ISSUE THREAD

**Issue by toastsandwich** [muruga21/LoadDistrix#5]
Allowing user to have config file types like JSON, yaml, yml, toml ..etc.

**Comment by muruga21** [comment]
@toastsandwich Hey man, could you elaborate the issue..

**Comment by toastsandwich** [comment]
You guys are making load balancer which is reading config as json, but what if developer is having config file with type yaml or toml or json or anyother, we can allow him to write this in single file allowing robustness and easy to write configuration file.

for example:

# with constraint of json file
the developer is using config.toml he will need to write json file as well

config.toml
[server]
....
[db]
...

lb.json
content...


# With multiple file extension
config.toml
[server]
...
[loadbalancer]
...
[db]
...


this is the idea for feature.

**Comment by muruga21** [comment]
@toastsandwich Yup its a great one..

do you want to contribute to this.. shall i assign it to you ?

**Comment by toastsandwich** [comment]
> @toastsandwich Yup its a great one..
> 
> do you want to contribute to this.. shall i assign it to you ?

yes please

**Comment by toastsandwich** [comment]
@muruga21  can i get access to create branch then i will raise pr.

**Comment by toastsandwich** [comment]
Also I was thinkining, why are we not making the load balancer a package.

**Comment by toastsandwich** [comment]
Hey there seems a problem in readme file

**Comment by toastsandwich** [comment]
@muruga21 can you please add label for hacktober as well ??

**Comment by muruga21** [comment]
@toastsandwich i too thought to make it as a package.. if you can raise it as new issue i will assign it to you

**Comment by toastsandwich** [comment]
@muruga21 i am so sorry i am asking this again but can you also add hackoctoberfest-accepted
