### ISSUE TITLE
Graceful Shutdown for HTTP Server

### ISSUE THREAD

**Issue by vidhvath28** [muruga21/LoadDistrix#8]
The current load balancer implementation lacks a graceful shutdown mechanism. This means that when the server receives termination signals (e.g., SIGINT or SIGTERM), it immediately stops processing new and ongoing requests, potentially leading to incomplete requests and loss of data. Implementing a graceful shutdown allows the server to stop accepting new requests, while still completing ongoing requests before shutting down. This ensures a smooth shutdown process and improves reliability during server restarts or deployments.

**Comment by vidhvath28** [comment]
I would like to work on this issue , kindly assign this issue to me .

**Comment by vidhvath28** [comment]
@muruga21 
My approach for this issue :-

1. Add a channel to listen for termination signals.
2. Implement the graceful shutdown logic by calling server.Shutdown() in response to termination signals.
3. Ensure that the shutdown process waits for all in-flight requests to complete.

**Comment by toastsandwich** [comment]
Nice find @vidhvath28, cant believe i missed it !!

**Comment by vidhvath28** [comment]
I have resolved the error and submitted a PR #9  , kindly please check it and consider this PR for Hacktoberfest and GSsoC by tagging it with hacktoberfest-accepted and gssoc-ext.

**Comment by toastsandwich** [comment]
I am a contributor for this repo too, @muruga21  please look into this.

**Comment by vidhvath28** [comment]
@toastsandwich  just few minutes back I have fixed the issue and submitted an PR for it

**Comment by vidhvath28** [comment]
@toastsandwich  can you please consider this PR for Hacktoberfest and GSsoC by tagging it with hacktoberfest-accepted and gssoc-ext.

**Comment by toastsandwich** [comment]
@vidhvath28 i am just contributor here, i am not project admin and for hacktober there must be tag added in repository as hacktober

**Comment by muruga21** [comment]
@vidhvath28 Great work man..!
